### ISSUE TITLE
Extreme CPU load 

### ISSUE THREAD

**Issue by HarHarLinks** [smorks/keepassnatmsg-proxy#4] opened 2022-02-23 00:17 UTC
`htop` on arch linux, keepass 2.50, keepassnatmsg v2.0.14.0, keepassnatmsg-proxy 0.0.8.40284, KeePassXC-Browser Version: 1.7.11, Vivaldi 5.2.2581.4 (Official Build) snapshot (64-bit), mono 6.12.0.122
![image](https://user-images.githubusercontent.com/2803622/155241485-15dbc10d-5fce-4d6f-970c-672e6e49459d.png)

This isn't all the time, but happens frequently and for minutes or so, I notice it because my otherwise idle CPU cooler will spin up pretty hard for a while so I check what's going on.

**Comment by smorks** [comment] 2022-02-23 14:51
hmmm, i'm guessing it must be getting stuck in a loop or something. i'll do some investigation into this.

if you could try and narrow it down when it happens, possibly when closing or locking keepass? or navigating to a new site or something? that would be helpful too. thanks!

**Comment by smorks** [comment] 2022-02-24 23:03
i was able to reproduce the problem in linux, just by closing keepass while the browser was running. will see if i can narrow down exactly what the problem is.

**Closed as completed** 2022-04-13 20:30 UTC
